_wandb:
    value:
        cli_version: 0.25.0
        e:
            li40s6o5kcti050258i83g6bp8gorqi9:
                args:
                    - --data_config
                    - preprocessed_input/data_config_sample.json
                codePath: 03-train.py
                codePathLocal: 03-train.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "943409860608"
                        used: "879009296384"
                email: hw7825@korea.ac.kr
                executable: /home/tech/anaconda3/envs/insite/bin/python
                git:
                    commit: 6a5568448b90868acf8b36d2fa3663919a003b40
                    remote: https://github.com/KU-MedAI/InSiteDTA.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-71270606-5771-3873-dff9-b1518d9c9442
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-2cf5594e-8b4f-66e4-9b80-9447130b971c
                host: korea-2
                memory:
                    total: "540659761152"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/tech/Hawon/InSiteDTA/03-train.py
                python: CPython 3.9.19
                root: /home/tech/Hawon/InSiteDTA
                startedAt: "2026-02-20T13:29:12.641454Z"
                writerId: li40s6o5kcti050258i83g6bp8gorqi9
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 1
                - 13
                - 16
            "4": 3.9.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
DCC_SR_threshold:
    value: 4
DCC_threshold:
    value: 0.5
DVO_threshold:
    value: 0.5
aff_loss_type:
    value: mse
aff_loss_weight:
    value: 0.2
batch_size:
    value: 48
ca_dropout:
    value: 0.1
ca_num_heads:
    value: 8
data_config:
    value: preprocessed_input/data_config_sample.json
dec_act:
    value: gelu
dec_drop_rate:
    value: 0.1
epochs:
    value: 300
feature_size:
    value: 48
gpu:
    value: 0
grad_accumulation_steps:
    value: 2
in_channels:
    value: 21
label_noise_std:
    value: 0.15
learning_rate:
    value: 1e-05
mol_act:
    value: mish
mol_cutoff_3d:
    value: 10
mol_dropout_3d:
    value: 0.15
mol_edge_num_fourier_feats_egnn:
    value: 3
mol_edge_num_gaussian_schnet:
    value: 50
mol_encoder_types:
    value:
        - attnfp
        - schnet
        - egnn
mol_hidden_channels:
    value: 128
mol_in_channels:
    value: 54
mol_num_filters_schnet:
    value: 128
mol_num_interactions_3d:
    value: 3
mol_num_layers:
    value: 2
mol_out_channels:
    value: 128
mol_soft_edge_egnn:
    value: false
num_workers:
    value: 6
optimizer:
    value: adamw
out_channels:
    value: 1
patience:
    value: 15
pocket_loss_types:
    value:
        - soft_dice
        - bce
pocket_loss_weight:
    value: 2
recon_loss_type:
    value: mse
recon_loss_weight:
    value: 1
rotation_prob:
    value: 0.3
save_dir:
    value: null
scheduler_T_mult:
    value: 1
scheduler_T_up:
    value: 10
scheduler_T0:
    value: 100
scheduler_eta_max:
    value: 0.001
scheduler_gamma:
    value: 0.7
seed:
    value: 312
sw_act:
    value: gelu
sw_attn_drop_rate:
    value: 0
sw_depths:
    value:
        - 2
        - 2
        - 2
sw_drop_path_rate:
    value: 0.1
sw_drop_rate:
    value: 0
sw_mlp_ratio:
    value: 4
sw_num_heads:
    value:
        - 3
        - 6
        - 12
sw_patch_size:
    value:
        - 2
        - 2
        - 2
sw_qkv_bias:
    value: true
sw_window_size:
    value: 7
tr_subset_ratio:
    value: 1
wandb_config:
    value: null
weight_decay:
    value: 0.001
